### PR TITLE
Data on the rest of the counties

### PR DESCRIPTION
**Pull request by KaterynaMinkina**
Hi! I am still not sure how to remove some spaces, so I would be grateful if you could do it for me. Is there some formula in excel to do it all at once? Some files have a different structure, so I followed that structure when was entering the data. And last: the data on Madison county, Ridgeland precinct 4 - were missing, so I put 0 for all results in this precinct. Thanks!

### CODE REVIEW

**Comment by dwillis** [comment]
@KaterynaMinkina thanks! generally Excel isn't the best way to remove things from multiple files, but you could do it in a text editor (like BBEdit for the Mac or Notepad++ on Windows) that allows you to find and replace things in an entire folder.

**Comment by KaterynaMinkina** [comment]
@dwillis got it! Thank you!

**Comment by warwickmm** [comment]
> And last: the data on Madison county, Ridgeland precinct 4 - were missing, so I put 0 for all results in this precinct.

@dwillis, would an empty entry be a better indication of a missing value?

**Comment by dwillis** [comment]
@warwickmm yes, let's distinguish between missing values and  0, which is a legitimate value in other cases.

**Comment by KaterynaMinkina** [comment]
@dwillis should I then change that file and leave just empty cells?

**Comment by dwillis** [comment]
@KaterynaMinkina yes please!

**Comment by KaterynaMinkina** [comment]
@dwillis I removed 0 values for Ridgeland, so now it`s just empty cells

**Pull request merged**
