### PR TITLE
Added Wayne

### PR DESCRIPTION
**Pull request by stedy**
After adding the same two files at almost the same time, rebased and just focused on Wayne county

### CODE REVIEW

**Comment by dwillis** [comment]
Thanks, @stedy and sorry about the duplication! Are you interested in doing another county? If so, I'll hold off.

**Comment by stedy** [comment]
yeah, basically I am a stay at home dad and I get these short snippets of time here and there which is perfect for this type of work. Happy to keep on this issue or shift my focus elsewhere as needed.

**Comment by dwillis** [comment]
By all means, keep at it - if you like, leave a comment here with the count(ies) you're working on.

**Comment by stedy** [comment]
ok, sure I will finish Walthall, Washington and Webster then we can close #28

**Pull request merged**
