### PR TITLE
Updates to both files

### PR DESCRIPTION
**Pull request by peter-redistricting-data-hub**
Changes as discussed in the issues I opened. This is one of my first times using Git on a public project like this, so curious if there is something I missed for the file changes on the csv to be more helpful.

### CODE REVIEW

**Comment by peter-redistricting-data-hub** [comment]
Made some minor changes based on the feedback from the automated scripts. There still will be some issues, but I don't think they'll be for 2023

**Comment by peter-redistricting-data-hub** [comment]
Okay so the remaining 2023 one is duplicate precincts for a District Attorney office, which is not something I'd changed

**Comment by warwickmm** [comment]
Thanks @peter-redistricting-data-hub.  If these changes address all the issues described in #186, then you can link that issue to this pull request under the "Development" section on the right.  That way, merging this pull request will automatically close that issue.

**Comment by peter-redistricting-data-hub** [comment]
Screen Shot 2024-01-30 at 5 27 01 PM
My apologies if this is basic stuff, but not seeing that option

**Comment by warwickmm** [comment]
Ah, no worries.  Perhaps the permissions are limited.  I created the link.

image

**Pull request merged**
