### PR TITLE
Update data on w-p precincts

### PR DESCRIPTION
**Pull request by KaterynaMinkina**
It says that some checks were not successful for Panola precincts. I can`t figure out the problem, could you help me with that? Thanks!

### CODE REVIEW

**Comment by warwickmm** [comment]
> It says that some checks were not successful for Panola precincts. I can`t figure out the problem, could you help me with that?

It looks like there are some tab characters `\t` appearing in some of the files.  We can easily remove them later if it's difficult for you to do so.

**Comment by dwillis** [comment]
@KaterynaMinkina thanks! i can clean up the tab characters on my end. really appreciate your work on this!

**Comment by KaterynaMinkina** [comment]
@dwillis no problem! Thank you for cleaning that up! I will finish the last few precincts next week!

**Comment by dwillis** [comment]
@KaterynaMinkina thanks!

**Pull request merged**
